# Find fpm -- this module looks for fpm
# Note: Install with
#   sudo gem install fpm
#
# FPM_EXECUTABLE - the full path to FPM
# FPM_FOUND - If false, don't attempt to use FPM.

FIND_PROGRAM(FPM_EXECUTABLE NAMES fpm PATHS /usr/local/bin)
MARK_AS_ADVANCED(FPM_EXECUTABLE)

IF (NOT FPM_EXECUTABLE)
SET(FPM_FOUND "NO")
ELSE (NOT FPM_EXECUTABLE)
SET(FPM_FOUND "YES")
ENDIF (NOT FPM_EXECUTABLE)

IF (NOT FPM_FOUND AND FPM_FIND_REQUIRED)
MESSAGE(FATAL_ERROR "Could not find FPM")
ENDIF (NOT FPM_FOUND AND FPM_FIND_REQUIRED)

